
name: finance-chatbot
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - cuda-toolkit=12.1
  - pytorch
  - torchvision
  - numpy
  - pip:
      - gradio==3.16.2
      - transformers==4.34.0
      - pytesseract
      - pdf2image
      - Pillow
